// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { ScreenVariantProvider } from "../components/plasmic/\u5BD2\u8292/PlasmicGlobalVariant__Screen";
import { Plasmic成都寒芒科技有限公司 } from "../components/plasmic/\u5BD2\u8292/Plasmic\u6210\u90FD\u5BD2\u8292\u79D1\u6280\u6709\u9650\u516C\u53F8";

function 成都寒芒科技有限公司() {
  // Use Plasmic成都寒芒科技有限公司 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic成都寒芒科技有限公司 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic成都寒芒科技有限公司 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return <Plasmic成都寒芒科技有限公司 />;
}

export default 成都寒芒科技有限公司;
