// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { ScreenVariantProvider } from "../components/plasmic/\u5BD2\u8292/PlasmicGlobalVariant__Screen";
import { Plasmic餐饮 } from "../components/plasmic/\u5BD2\u8292/Plasmic\u9910\u996E";

function 餐饮() {
  // Use Plasmic餐饮 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic餐饮 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic餐饮 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return <Plasmic餐饮 />;
}

export default 餐饮;
